/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : McuSDCard.c
**     Project     : FRDM-K64F_Generator
**     Processor   : MK64FN1M0VLL12
**     Component   : SD_Card
**     Version     : Component 01.184, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-06-20, 13:08, # CodeGen: 327
**     Abstract    :
**         Implements interface to SD card for FatFs
**     Settings    :
**          Component name                                 : McuSDCard
**          Block size                                     : 512
**          Cmd wait counter                               : 10
**          Wait Ready Timeout (ms)                        : 500
**          Wait Cmd Timeout (ms)                          : 100
**          Receive Block Timeout (ms)                     : 500
**          SPI Block Transfer                             : no
**          Hardware                                       : 
**            SW SPI                                       : Enabled
**              SPI                                        : McuGenericSWSPI
**            HW SPI                                       : Disabled
**            SPI Read/Write Macros                        : Disabled
**            Slave Select                                 : Enabled
**              LDD SS                                     : Enabled
**                Slave Select Pin                         : LDDSS
**              non-LDD SS                                 : Disabled
**            Activate                                     : Disabled
**            Card detection                               : Disabled
**            Report 'Card present' if no Card detection pin: yes
**            Write protection                             : Disabled
**          System                                         : 
**            Wait                                         : McuWait
**            Timeout                                      : McuTimeout
**            RTOS                                         : Enabled
**              RTOS                                       : McuRTOS
**     Contents    :
**         Activate         - void McuSDCard_Activate(void);
**         Deactivate       - void McuSDCard_Deactivate(void);
**         isWriteProtected - bool McuSDCard_isWriteProtected(void);
**         CardPresent      - bool McuSDCard_CardPresent(void);
**         WaitReady        - uint8_t McuSDCard_WaitReady(void);
**         ReceiveDataBlock - bool McuSDCard_ReceiveDataBlock(uint8_t *data, uint16_t nofBytes);
**         SendDataBlock    - bool McuSDCard_SendDataBlock(uint8_t *data, uint8_t token, uint16_t nofBytes);
**         SendCmd          - uint8_t McuSDCard_SendCmd(uint8_t cmd, uint32_t arg);
**         SetSlowMode      - void McuSDCard_SetSlowMode(void);
**         SetFastMode      - void McuSDCard_SetFastMode(void);
**         InitCommChannel  - void McuSDCard_InitCommChannel(void);
**         Deinit           - uint8_t McuSDCard_Deinit(void* unused);
**         Init             - uint8_t McuSDCard_Init(void* unused);
**
**     * Copyright (c) 2012-2017, Erich Styger
**      * Web:         https://mcuoneclipse.com
**      * SourceForge: https://sourceforge.net/projects/mcuoneclipse
**      * Git:         https://github.com/ErichStyger/McuOnEclipse_PEx
**      * All rights reserved.
**      *
**      * Redistribution and use in source and binary forms, with or without modification,
**      * are permitted provided that the following conditions are met:
**      *
**      * - Redistributions of source code must retain the above copyright notice, this list
**      *   of conditions and the following disclaimer.
**      *
**      * - Redistributions in binary form must reproduce the above copyright notice, this
**      *   list of conditions and the following disclaimer in the documentation and/or
**      *   other materials provided with the distribution.
**      *
**      * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**      * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**      * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**      * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**      * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**      * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**      * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**      * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**      * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**      * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file McuSDCard.c
** @version 01.00
** @brief
**         Implements interface to SD card for FatFs
*/         
/*!
**  @addtogroup McuSDCard_module McuSDCard module documentation
**  @{
*/         

/* MODULE McuSDCard. */

#include "platform.h"
#include "diskio.h"
#include "McuSDCard.h"
#include "spi.h"
#include "wait.h"


// Chip select
#define SS_SELECT_SLAVE()     GPIOC->PCOR = (1<<1)           // PTC1 (low active)
#define SS_UNSELECT_SLAVE()   (GPIOC->PSOR = (1<<1))           // PTC1 (low active)
#define SS_SET_MUX()          PORTC->PCR[1] = PORT_PCR_MUX(1)  // PTC1 Mux as GPIO
#define SS_SET_PDDR()         GPIOC->PDDR |= (1<<1)          // PTC1 as output


static volatile DSTATUS Stat = STA_NOINIT; /* Disk status */
static uint8_t CardType = CT_SD1;       /* Card type flags */


static uint8_t currentSpeedMode = McuSDCard_ACTIVATE_MODE_NONE; /* current speed mode */

enum { /* SD card response codes */
  McuSDCard_OK = 0,
  McuSDCard_IDLE = 1
};


/* different wait counters to deal with slow SD cards */
#define McuSDCard_TIMEOUT_READY_MS       500 /* user configured wait timeout until the device is ready */
#define McuSDCard_TIMEOUT_CMD_MS         100 /* user configured wait timeout for commands */
#define McuSDCard_TIMEOUT_READ_BLOCK_MS  500 /* user configured wait timeout for reading a data block */

#define SPI_DUMMY_BYTE 0xff

#define McuSDCard_DUMMY 0xff /* SPI dummy value */

#define ALENGTH(x)  (sizeof(x) / sizeof((x)[0]))

// R1 Response Format
#define R1_NO_RESPONSE          (0xFF)
#define R1_RESPONSE_RECV        (0x80)
#define R1_IDLE_STATE           (1 << 0)
#define R1_ERASE_RESET          (1 << 1)
#define R1_ILLEGAL_COMMAND      (1 << 2)
#define R1_COM_CRC_ERROR        (1 << 3)
#define R1_ERASE_SEQUENCE_ERROR (1 << 4)
#define R1_ADDRESS_ERROR        (1 << 5)
#define R1_PARAMETER_ERROR      (1 << 6)




#define sdSelectSlave()     SS_SELECT_SLAVE()
#define sdUnselectSlave()   SS_UNSELECT_SLAVE()


//#define Low()    (GPIOC_PCOR = (1<<8))           // PTC1 (low active)
//#define High()   (GPIOC_PSOR = (1<<8))           // PTC1 (low active)



bool sdWaitReady(uint16_t ms)
{
  uint32_t start = waitStartWatch();
  do
  {
    // wait until MISO goes high
    if (spiWriteReadByte(SPI_DUMMY_BYTE) == 0xFF) return TRUE;
  } while(waitGetTimeMs(start) < ms);
  return FALSE;
}


/**
 * Switches to slow mode SPI communication speed:  <400kHz
 */
void sdSetLowSpeed(void)
{
  if (currentSpeedMode!=McuSDCard_ACTIVATE_MODE_SLOW) {
    currentSpeedMode = McuSDCard_ACTIVATE_MODE_SLOW;
    spiSetSpeed(TRUE, 2, 6, 2, 3); // 375 kHz
  }
}


/**
 * Switches to fast mode SPI communication speed ~20 MHz
 */
void sdSetHighSpeed(void)
{
  if (currentSpeedMode!=McuSDCard_ACTIVATE_MODE_FAST) {
    currentSpeedMode = McuSDCard_ACTIVATE_MODE_FAST;
    spiSetSpeed(TRUE, 1, 0, 0, 0); // 20 MHz
  }
}



/**
 * Initialize a Drive
 *
 * @param[in] drv
 *   Physical drive number (0..)
 * @returns disk status
 */
DSTATUS McuSDCard_disk_initialize(uint8_t drv)
{
  uint8_t n, cmd, ty, ocr[4];

  (void)drv; /* not used */
  if (Stat&STA_NODISK) {
    return Stat;                        /* No card in the socket */
  }
  if (McuSDCard_Init() != ERR_OK) {
    return STA_NOINIT;
  }
  ty = 0;
  if (McuSDCard_SendCmd(McuSDCard_CMD0, 0) == 1) { /* Enter Idle state */
    if (McuSDCard_SendCmd(McuSDCard_CMD8, 0x1AA) == 1) { /* SDHC */
      for (n = 0; n < 4; n++) {
        ocr[n] = McuSDCard_ReceiveByte(); /* Get trailing return value of R7 resp */
      }
      if (ocr[2] == 0x01 && ocr[3] == 0xAA) { /* The card can work at vdd range of 2.7-3.6V */
        while (McuSDCard_SendCmd(McuSDCard_ACMD41, 1UL << 30)) {
          /* Wait for leaving idle state (ACMD41 with HCS bit) */
        }

        if (McuSDCard_SendCmd(McuSDCard_CMD58, 0) == 0) { /* Check CCS bit in the OCR */
          for (n = 0; n < 4; n++) {
            ocr[n] = McuSDCard_ReceiveByte();
          }
          ty = (uint8_t)((ocr[0] & 0x40) ? CT_SD2 | CT_BLOCK : CT_SD2); /* SDv2 */
        }
      }
    } else {                            /* SDSC or MMC */
      if (McuSDCard_SendCmd(McuSDCard_ACMD41, 0) <= 1) {
        ty = CT_SD1; cmd = McuSDCard_ACMD41; /* SDv1 */
      } else {
        ty = CT_MMC; cmd = McuSDCard_CMD1; /* MMCv3 */
      }
      while (McuSDCard_SendCmd(cmd, 0)) {
        /* Wait for leaving idle state */
      }
      if (McuSDCard_SendCmd(McuSDCard_CMD16, McuSDCard_BLOCK_SIZE) != 0) { /* Set R/W block length  */
        ty = 0;
      }
    }
    sdSetHighSpeed();
  }
  CardType = ty;
  Stat &= ~STA_NOINIT;                  /* Clear STA_NOINIT */
  return Stat;
}


/**
 * Return Disk Status
 *
 * @param[in] drv
 *   Physical drive number (0..)
 * @returns disk status
 */
DSTATUS McuSDCard_disk_status (uint8_t drv)
{
  (void)drv; /* not used */
  return Stat;
}


/**
 * Read Sector(s)
 *
 * @param[in] drv
 *   Physical drive number (0..)
 * @param[in] *buff
 *   Data buffer to store read data
 * @param[in] sector
 *   Sector address (LBA)
 * @param[in] count
 *   Number of sectors to read (1..255)
 */
DRESULT McuSDCard_disk_read (uint8_t drv, uint8_t *buff, uint32_t sector, unsigned int count)
{
  (void)drv; /* not used */
  if (!count) {
    return RES_PARERR;
  }
  if (Stat & STA_NOINIT) {
    return RES_NOTRDY;
  }
  if (!(CardType & CT_BLOCK)) {
    sector *= McuSDCard_BLOCK_SIZE;     /* Convert to byte address if needed */
  }
  if (count == 1) {                     /* Single block read */
    if (   (McuSDCard_SendCmd(McuSDCard_CMD17, sector) == 0) /* READ_SINGLE_BLOCK */
        && McuSDCard_ReceiveDataBlock(buff, McuSDCard_BLOCK_SIZE))
    {
      count = 0;
    }
  } else {                              /* Multiple block read */
    if (McuSDCard_SendCmd(McuSDCard_CMD18, sector) == 0) { /* READ_MULTIPLE_BLOCK */
      do {
        if (!McuSDCard_ReceiveDataBlock(buff, McuSDCard_BLOCK_SIZE)) {
          break;
        }
        buff += McuSDCard_BLOCK_SIZE;
      } while (--count);
      (void)McuSDCard_SendCmd(McuSDCard_CMD12, 0); /* STOP_TRANSMISSION */
    }
  }
  return count ? RES_ERROR : RES_OK;
}


#if _READONLY == 0

/**
 * Read Sector(s)
 *
 * @param[in] drv
 *   Physical drive number (0..)
 * @param[out] *buff
 *   Data Data to be written
 * @param[in] sector
 *   Sector address (LBA)
 * @param[in] count
 *   Number of sectors to write (1..255)
 */
DRESULT McuSDCard_disk_write (uint8_t drv, const uint8_t *buff, uint32_t sector, unsigned int count)
{
  (void)drv; /* not used */
  if (!count) {
    return RES_PARERR;
  }
  if (Stat & STA_NOINIT) {
    return RES_NOTRDY;
  }
  if (Stat & STA_PROTECT) {
    return RES_WRPRT;
  }
  if (!(CardType & CT_BLOCK)) {
    sector *= McuSDCard_BLOCK_SIZE;     /* Convert to byte address if needed */
  }
  if (count == 1) {                     /* Single block write */
    if (  (McuSDCard_SendCmd(McuSDCard_CMD24, sector) == 0) /* WRITE_BLOCK */
        && McuSDCard_SendDataBlock((uint8_t*)buff, 0xFE, McuSDCard_BLOCK_SIZE))
    {
      count = 0;
    }
  } else {                              /* Multiple block write */
    if (CardType & CT_SDC) {
      (void)McuSDCard_SendCmd(McuSDCard_ACMD23, count);
    }
    if (McuSDCard_SendCmd(McuSDCard_CMD25, sector) == 0) { /* WRITE_MULTIPLE_BLOCK */
      do {
        if (!McuSDCard_SendDataBlock((uint8_t*)buff, 0xFC, McuSDCard_BLOCK_SIZE)) {
          break;
        }
        buff += McuSDCard_BLOCK_SIZE;
      } while (--count);
      if (!McuSDCard_SendDataBlock(0, 0xFD, McuSDCard_BLOCK_SIZE)) { /* STOP_TRAN token */
        count = 1;
      }
    }
  }
  return count ? RES_ERROR : RES_OK;
}
#endif /* _READONLY */



/*-----------------------------------------------------------------------*/
/* Miscellaneous Functions                                               */
static uint8_t chk_power(void) { return 1;}
static void power_off(void) {}
static void power_on(void) {}
/*-----------------------------------------------------------------------*/
DRESULT McuSDCard_disk_ioctl (
        uint8_t drv,                    /* Physical drive number (0..) */
        uint8_t ctrl,                   /* Control code */
        void *buff                      /* Buffer to send/receive control data */
)
{
  DRESULT res = RES_OK;
  uint8_t n, csd[16], *ptr = (uint8_t*)buff;
  uint16_t csize;

  (void)drv; /* not used */
  if (ctrl == CTRL_POWER) {
    switch (*ptr) {
      case 0:                           /* Sub control code == 0 (POWER_OFF) */
        if (chk_power()) {
        /*lint -save -e522 Highest operation lacks side effect */
          power_off();                  /* Power off */
        /*lint -restore */
        }
        break;
      case 1:                           /* Sub control code == 1 (POWER_ON) */
        /*lint -save -e522 Highest operation lacks side effect */
        power_on();                     /* Power on */
        /*lint -restore */
        break;
      case 2:                           /* Sub control code == 2 (POWER_GET) */
        *(ptr+1) = (uint8_t)chk_power();
        break;
      default:
        res = RES_PARERR;
    } /* switch */
  } else {
    if (Stat & STA_NOINIT) {
      return RES_NOTRDY;
    }
    switch (ctrl) {
      case CTRL_SYNC :                  /* Make sure that no pending write process. Do not remove this or written sector might not left updated. */

        if (!sdWaitReady(McuSDCard_TIMEOUT_READY_MS)) {
          res = RES_ERROR;
        }
        break;
      case MMC_GET_READ_BL_LEN:         /* get Block Length */
        if ((McuSDCard_SendCmd(McuSDCard_CMD9, 0) == 0) && McuSDCard_ReceiveDataBlock(csd, 16)) {
          switch((csd[5]&15)) {         /* READ_BL_LEN is either 9, 10 or 11, end the block size is 2^READ_BL_LEN */
            case 9: *(uint16_t*)ptr = 512; break;
            case 10: *(uint16_t*)ptr = 1024; break;
            case 11: *(uint16_t*)ptr = 2048; break;
            default: *(uint16_t*)ptr = 0; break; /* illegal */
          }
        }
        break;
      case MMC_GET_SDC_VERSION:         /* get CSD Version (1 byte: 1 for 1.xx or MMC, 2 for 2.0 */
        if ((McuSDCard_SendCmd(McuSDCard_CMD9, 0) == 0) && McuSDCard_ReceiveDataBlock(csd, 16)) {
          if ((csd[0] >> 6) == 1) {     /* SDC ver 2.00 */
            *ptr = 2;
          } else {                      /* SDC ver 1.XX or MMC*/
            *ptr = 1;
          }
        }
        break;
      case GET_SECTOR_COUNT :           /* Get number of sectors on the disk (uint32_t) */
        if ((McuSDCard_SendCmd(McuSDCard_CMD9, 0) == 0) && McuSDCard_ReceiveDataBlock(csd, 16)) {
          if ((csd[0] >> 6) == 1) {     /* SDC ver 2.00 */
            csize = (uint16_t)(csd[9] + ((uint16_t)csd[8] << 8) + 1);
            *(uint32_t*)buff = (uint32_t)csize << 10;
          } else {                      /* SDC ver 1.XX or MMC*/
            n = (uint8_t)((csd[5] & 15) + ((csd[10] & 128) >> 7) + ((csd[9] & 3) << 1) + 2);
            csize = (uint16_t)((csd[8] >> 6) + ((uint16_t)csd[7] << 2) + ((uint16_t)(csd[6] & 3) << 10) + 1);
            *(uint32_t*)buff = (uint32_t)csize << (uint8_t)(n - 9);
          }
        }
        break;
      case GET_SECTOR_SIZE :            /* Get R/W sector size (uint16_t) */
        *(uint16_t*)buff = McuSDCard_BLOCK_SIZE;
        break;
      case GET_BLOCK_SIZE :             /* Get erase block size in unit of sector (uint32_t) */
        if (CardType & CT_SD2) {        /* SDC ver 2.00 */
          if (McuSDCard_SendCmd(McuSDCard_ACMD13, 0) == 0) { /* Read SD status */
            (void)McuSDCard_ReceiveByte();
            if (McuSDCard_ReceiveDataBlock(csd, 16)) { /* Read partial block */
              for (n = 64 - 16; n; n--) {
                (void)McuSDCard_ReceiveByte(); /* Purge trailing data */
              }
              *(uint32_t*)buff = 16UL << (csd[10] >> 4);
            }
          }
        } else {                        /* SDC ver 1.XX or MMC */
          if ((McuSDCard_SendCmd(McuSDCard_CMD9, 0) == 0) && McuSDCard_ReceiveDataBlock(csd, 16)) {        /* Read CSD */
            if (CardType & CT_SD1) {    /* SDC ver 1.XX */
              *(uint32_t*)buff = (uint32_t)((((csd[10] & 63) << 1) + ((uint16_t)(csd[11] & 128) >> 7) + 1) << (uint8_t)((csd[13] >> 6) - 1));
            } else {                    /* MMC */
              *(uint32_t*)buff = (uint32_t)(((uint16_t)((csd[10] & 124) >> 2) + 1) * (((csd[11] & 3) << 3) + ((csd[11] & 224) >> 5) + 1));
            }
          }
        }
        break;
      case MMC_GET_TYPE :               /* Get card type flags (1 byte) */
        *ptr = CardType;
        break;

      case MMC_GET_CSD :                /* Receive CSD as a data block (16 bytes) */
         if (!(McuSDCard_SendCmd(McuSDCard_CMD9, 0) == 0 /* READ_CSD */
            && McuSDCard_ReceiveDataBlock(ptr, 16)))
         {
           res = RES_PARERR;
         }
         break;
      case MMC_GET_CID :                /* Receive CID as a data block (16 bytes) */
        if (!(McuSDCard_SendCmd(McuSDCard_CMD10, 0) == 0 /* READ_CID */
            && McuSDCard_ReceiveDataBlock(ptr, 16)))
        {
          res = RES_PARERR;
        }
        break;

      case MMC_GET_OCR :                /* Receive OCR as an R3 resp (4 bytes) */
        if (McuSDCard_SendCmd(McuSDCard_CMD58, 0) == 0) { /* READ_OCR */
          for (n = 4; n; n--) {
            *ptr++ = McuSDCard_ReceiveByte();
          }
        } else {
          res = RES_PARERR;
        }
        break;

      case MMC_GET_SDSTAT :             /* Receive SD status as a data block (64 bytes) */
        if (McuSDCard_SendCmd(McuSDCard_ACMD13, 0) == 0) { /* SD_STATUS */
          (void)McuSDCard_ReceiveByte();
          if (!McuSDCard_ReceiveDataBlock(ptr, 64)) {
            res = RES_PARERR;
          }
        } else {
          res = RES_PARERR;
        }
        break;

      case MMC_GET_DRIVER_VERSION:      /* 1 byte: return: 0 SPI driver, 1 LLD SDHC driver */
        *ptr = 0;
        break;

      default:
        res = RES_PARERR;
    } /* switch */
  } /* if-else */
  return res;
}


/*
** ===================================================================
**     Method      :  McuSDCard_ReceiveDataBlock (component SD_Card)
**     Description :
**         Retrieve a data block from the device
**     Parameters  :
**         NAME            - DESCRIPTION
**       * data            - Pointer to data buffer
**         nofBytes        - number of bytes to retrieve,
**                           must be a multiple of 4
**     Returns     :
**         ---             - TRUE if reading was going fine, FALSE
**                           otherwise.
** ===================================================================
*/
bool McuSDCard_ReceiveDataBlock(uint8_t *data, uint16_t nofBytes)
{
  uint8_t tmp;
  uint32_t start;
  word cnt = 512; /* polling counter */

  sdSelectSlave();
  /* poll response */
  do {
    tmp = spiWriteReadByte(McuSDCard_DUMMY); /* send dummy value, poll response */
    cnt--;
  } while (tmp==0xFF && cnt>0);
  if (tmp==0xFF) { /* polling not successful, now poll for a longer period of time */
    //timeout = McuTimeout_GetCounter(McuSDCard_TIMEOUT_READ_BLOCK_MS/McuTimeout_TICK_PERIOD_MS); /* timeout */
    start = waitStartWatch();
    for (;;) {                          /* will timeout */
      tmp = spiWriteReadByte(McuSDCard_DUMMY); /* send dummy value, poll response */
      if (tmp!=0xFF) {
        break;
      }
      // waitMs(1);
      // polled already for a tick period: use RTOS wait in order to balance CPU cycles
      if (waitGetTimeMs(start) > McuSDCard_TIMEOUT_READ_BLOCK_MS) {
        break;
      }
    } /* for */
  } /* if */
  if (tmp != 0xFE) {                    /* if it is not expected response, return with error */
    sdUnselectSlave();
    return FALSE;
  }
  spiWriteReadBuf(NULL, nofBytes, data);
  spiWriteReadBuf(NULL, 2, NULL);         /* checksum Bytes not needed */
  //spiWriteReadByte(McuSDCard_DUMMY);
  //spiWriteReadByte(McuSDCard_DUMMY);
  sdUnselectSlave();
  return TRUE;
}

/*
** ===================================================================
**     Method      :  McuSDCard_SendDataBlock (component SD_Card)
**     Description :
**         Send a data block to the device
**     Parameters  :
**         NAME            - DESCRIPTION
**       * data            - Pointer to data blocks with 512 bytes
**                           each
**         token           - data/stop token
**         nofBytes        - Number of bytes to send
**     Returns     :
**         ---             - Returns TRUE for success, FALSE for
**                           failure.
** ===================================================================
*/
bool McuSDCard_SendDataBlock(uint8_t *data, uint8_t token, uint16_t nofBytes)
{
  uint8_t resp;

  sdSelectSlave();

  if (!sdWaitReady(McuSDCard_TIMEOUT_READY_MS)) {
    return FALSE; // device not ready
  }


  spiWriteReadByte(token);           /* Xmit data token */
  if (token != 0xFD) {                  /* Is data token, not STOP_TRAN */
    spiWriteReadBuf(data, nofBytes, NULL);
    spiWriteReadBuf(NULL, 2, NULL);         /* 2x CRC (Dummy) */

    resp = spiWriteReadByte(McuSDCard_DUMMY); /* write dummy value, receive data response */
    if ((resp&0x1F) != 0x05) {          /* If not accepted, return with error */
      sdUnselectSlave();
      return FALSE;
    }
    /* if we do not poll the device for its busy state, we need to provide at least 8 clocks (dummy cycle).
     * See http://elm-chan.org/docs/mmc/mmc_e.html:
     *    In principle of the SPI mode, the CS signal must be asserted during a transaction,
     *    however there is an exception to this rule. When the card is busy, the host controller
     *    can deassert CS to release SPI bus for any other SPI devices. The card will drive DO signal
     *    low again when reselect it during internal process is in progress.
     *    Therefore a preceding busy check (wait ready immediately before command and data packet)
     *    instead of post wait can eliminate waste wait time. In addition the internal process is initiated
     *    a byte after the data response, this means eight clocks are required to initiate internal write operation.
     */
    spiWriteReadByte(McuSDCard_DUMMY);
  }
  sdUnselectSlave();
  return TRUE;
}

/*
** ===================================================================
**     Method      :  McuSDCard_SendCmd (component SD_Card)
**     Description :
**         Sends a command to the device and returns the response
**     Parameters  :
**         NAME            - DESCRIPTION
**         cmd             - Command to send
**         arg             - command argument
**     Returns     :
**         ---             - device response
** ===================================================================
*/
uint8_t McuSDCard_SendCmd(uint8_t cmd, uint32_t arg)
{
  uint8_t buf[6];
  uint8_t res;

  if (cmd & 0x80) {                       /* ACMD<n> is the command sequence of CMD55-CMD<n> */
    cmd &= 0x7F;
    res = McuSDCard_SendCmd(McuSDCard_CMD55, 0);
    if (res > 1) {
      return res;
    }
  }

  sdSelectSlave();

  /* Select the card and wait for ready */
  if (!sdWaitReady(McuSDCard_TIMEOUT_READY_MS)){
    return 0xFF;
  }

  buf[0] = cmd;                     // Start + Command index
  buf[1] = (uint8_t)(arg >> 24);    // Argument[31..24]
  buf[2] = (uint8_t)(arg >> 16);    // Argument[23..16]
  buf[3] = (uint8_t)(arg >> 8);     // Argument[15..8]
  buf[4] = (uint8_t)(arg >> 0);     // Argument[7..0]

  // default checksum is 0xFF
  buf[5] = 0xFF;

  // CMD0 and CMD8 needs a checksum. Using precalculated checksum values
  if (cmd == McuSDCard_CMD0) buf[5] = 0x95; // Valid CRC for CMD0(0)
  if (cmd == McuSDCard_CMD8) buf[5] = 0x87; // Valid CRC for CMD8(0x1AA)

  // Send command
  spiWriteReadBuf(buf, 6, NULL);

  // Wait for response. The response is sent back within
  // the command response time (NCR): 0 to 8 bytes
  for (uint8_t i=0; i<10; i++)
  {
    res = spiWriteReadByte(0xFF);
    if ((res & 0x80) == 0) break;
  }

  sdUnselectSlave();
  return res;
}



uint8_t sdSendCmd(uint8_t cmd, uint32_t arg)
{
  uint8_t buf[6];
  uint8_t res;

  buf[0] = cmd;                     // Start + Command index
  buf[1] = (uint8_t)(arg >> 24);    // Argument[31..24]
  buf[2] = (uint8_t)(arg >> 16);    // Argument[23..16]
  buf[3] = (uint8_t)(arg >> 8);     // Argument[15..8]
  buf[4] = (uint8_t)(arg >> 0);     // Argument[7..0]

  // default checksum is 0xFF
  buf[5] = 0xFF;

  // CMD0 and CMD8 needs a checksum. Using precalculated checksum values
  if (cmd == McuSDCard_CMD0) buf[5] = 0x95; // Valid CRC for CMD0(0)
  if (cmd == McuSDCard_CMD8) buf[5] = 0x87; // Valid CRC for CMD8(0x1AA)

  // Send command
  spiWriteReadBuf(buf, 6, NULL);

  // The received byte immediataly following CMD12 is a stuff byte,
  // it should be discarded before receive the response of the CMD12.
  if (cmd == McuSDCard_CMD12) spiWriteReadByte(0xFF);

  // Wait for response. The response is sent back within
  // the command response time (NCR): 0 to 8 bytes
  for (uint8_t i=0; i<10; i++)
  {
    res = spiWriteReadByte(0xFF);
    // response R1 => bit7 must be 0
    if ((res & 0x80) == 0) break;
  }

  return res;
}




uint8_t sdSendCmdEx(uint8_t cmd, uint32_t arg, uint32_t *response)
{
  uint32_t result;
  sdSelectSlave();

  for (int i=0; i<3; i++)
  {
    if (cmd & 0x80)
    {
      result = sdSendCmd(McuSDCard_CMD55, 0);     // Send CMD55 for APP command (ACMD) first
      if (result > 1) return result;              // if result==1 => no error and card is in idle state
    }

    cmd &= 0x7F;
    result = sdSendCmd(cmd, arg);
    if (result == R1_NO_RESPONSE)
    {
      dlog("No response of CMD: %d", cmd);
      continue;
    }
    break;
  }

  if (response) {
    *response = result;
  }

  if (result == R1_NO_RESPONSE)
  {
    sdUnselectSlave();
    dlog("No response CMD:%d response: 0x%x\r\n", cmd, result);
    return EC_NO_ANSWER;
  }

  if (result & R1_COM_CRC_ERROR)
  {
    sdUnselectSlave();
    dlog("CRC error CMD:%d response: 0x%x\r\n", cmd, result);
    return EC_CRC_ERROR;
  }

  if (result & R1_ILLEGAL_COMMAND)
  {
    sdUnselectSlave();
    dlog("Illegal command CMD:%d response: 0x%x\r\n", cmd, result);
    return EC_INVALID_CMD;;
  }

  switch (cmd)
  {
    case McuSDCard_CMD8 :
      spiWriteReadBuf(NULL, 4, (uint8_t*)&result);
      break;
  }


  if (response) {
      *response = result;
    }

  sdUnselectSlave();

  return 0;
}



/**
 * Initializes the driver
 *
 * The behavior of SD cards in SPI mode is basically the same as for any SPI slave device.
 * The maximum transfer rate of the SD card in SPI mode is 25 Mbps, but in the initialization process the
 * transfer rate must be less than 375 kbps. This is because the SPI mode of the SD cards is compatible with
 * the MMC cards, and MMC cards can only reach 375 kbps. After initialization, the SPI clock can be
 * changed to 25 Mbps.
 * Note that the SPI interface is defined with 'clock idle low polarity' and 'data shift on rising edge',
 * typically defined as well as 'Mode 0' (CPHA=0, CPOL=0). See http://elm-chan.org/docs/mmc/mmc_e.html
 *
 */
uint8_t McuSDCard_Init(void)
{
  uint8_t data[10] = { 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF };

  uint32_t response;
  //uint8_t buf[4];
  uint8_t result;
  //dword arg;
  //McuTimeout_CounterHandle timeout;
  //uint32_t start;
  //bool isTimeout = FALSE;
  //uint8_t cnt;


  // after voltage reaches 2.2V, need to wait at least 1 ms.
  // Then we need to set Data and CS/Chipselect high for at least 74 clocks
  waitMs(1);

  sdUnselectSlave();    // unselect slave (CS goes high)
  SS_SET_MUX();         // configure mux of Slave Select
  SS_SET_PDDR();        // configure port data direction of Slave Select

  sdSetLowSpeed();      // set the SPI clock to 375 kbps. This is required for compatibility across a wide range of SD and MMC cards.

  // Set DI and CS high and apply 74 or more clock pulses to SCLK.
  // The card will enter its native operating mode and go ready to accept native command.
  spiWriteReadBuf(data, ALENGTH(data), NULL);



  // send CMD0 (Reset or GoIdleState) command. All arguments are 0x00 for the reset command.
  // Reseting the MCU SPI master may not reset the on-board SDCard, in which case when
  // MCU power-on occurs the SDCard will resume operations as though there was no reset.
  // In this scenario the first CMD0 will not be interpreted as a command and get lost.
  // For some cards retrying the command overcomes this situation
  for (int i=0; i<5; i++)
  {
    result = McuSDCard_SendCmd(McuSDCard_CMD0, 0);
    if (result == R1_IDLE_STATE) break;
    waitMs(1);
  }

  //spiReadByte(FALSE);

  if (result != R1_IDLE_STATE)
  {
    dlog("No sd card, or could not put SD card in to SPI idle state");
    return EC_NO_ANSWER;
  }


  return EC_SUCCESS;

  // send CMD0 (Reset or GoIdleState) command. All arguments are 0x00 for the reset command.
  // Reseting the MCU SPI master may not reset the on-board SDCard, in which case when
  // MCU power-on occurs the SDCard will resume operations as though there was no reset.
  // In this scenario the first CMD0 will not be interpreted as a command and get lost.
  // For some cards retrying the command overcomes this situation
  for (int i=0; i<5; i++)
  {
    result = sdSendCmdEx(McuSDCard_CMD0, 0, NULL);
    if (result == R1_IDLE_STATE) break;
    waitMs(1);
  }

  //spiReadByte(FALSE);

  if (result != R1_IDLE_STATE)
  {
    dlog("No sd card, or could not put SD card in to SPI idle state");
    return EC_NO_ANSWER;
  }





  // Send interface condition command (CMD8)
  // - Checks whether the card can operate on the host supply voltage.
  // - Enabling expansion of existing command and response
  result = McuSDCard_SendCmd(McuSDCard_CMD8, 0x1AA);
  if (result == R1_IDLE_STATE)
  {
    // Card is SDHC
    // CMD8 has 4 more bytes
    spiWriteReadBuf(NULL, 4, (uint8_t*) &response);

    // Verify voltage (2.7-3.6V) and pattern for V2 version of card
    if ((response & 0xFFF) != 0x1AA)
    {
      dlog("CMD8 pattern mismatch");
      return EC_INVALID_OPERATION;
    }

  }
  else
  {

  }




//  if (McuSDCard_SendCmd(McuSDCard_CMD8, 0x1AA) == 1) { /* SDHC */
//    for (n = 0; n < 4; n++) {
//      ocr[n] = McuSDCard_ReceiveByte(); /* Get trailing return value of R7 resp */
//    }
//    if (ocr[2] == 0x01 && ocr[3] == 0xAA) { /* The card can work at vdd range of 2.7-3.6V */
//      while (McuSDCard_SendCmd(McuSDCard_ACMD41, 1UL << 30)) {
//        /* Wait for leaving idle state (ACMD41 with HCS bit) */
//      }
//
//      if (McuSDCard_SendCmd(McuSDCard_CMD58, 0) == 0) { /* Check CCS bit in the OCR */
//        for (n = 0; n < 4; n++) {
//          ocr[n] = McuSDCard_ReceiveByte();
//        }
//        ty = (uint8_t)((ocr[0] & 0x40) ? CT_SD2 | CT_BLOCK : CT_SD2); /* SDv2 */
//      }
//    }





  return EC_SUCCESS;

//
//  /* -------------------------------- IDLE Command -------------------------------- */
//  arg = 0;
//  //timeout = McuTimeout_GetCounter(McuSDCard_TIMEOUT_READY_MS/McuTimeout_TICK_PERIOD_MS); /* timeout */
//  start = waitStartWatch();
//  while (SendCommand(McuSDCard_CMD0, (uint8_t*)&arg, McuSDCard_IDLE) != ERR_OK) {
//    //if (McuTimeout_CounterExpired(timeout)) {
//    if (waitGetTimeMs(start) > McuSDCard_TIMEOUT_READY_MS) {
//      isTimeout = TRUE;                /* indicate a timeout */
//      break;
//    }
//  } /* while */
//  //McuTimeout_LeaveCounter(timeout);
//  if (isTimeout) {                      /* timeout */
//    return ERR_FAULT;
//  }
//
//
//
//
//
//  /* Send 8 SPI clocks (SS unasserted). */
//  sdSelectSlave();
//  SS_UNSELECT_SLAVE();               /* disable slave */
//  McuSDCard_SPI_WRITE(McuSDCard_DUMMY); /* dummy SPI cycle */
//  sdUnselectSlave();
//  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  McuSDCard_ReceiveByte (component SD_Card)
**
**     Description :
**         Receives a byte from the SPI bus
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
uint8_t McuSDCard_ReceiveByte(void)
{
  uint8_t data;
  sdSelectSlave();
  data = spiWriteReadByte(McuSDCard_DUMMY); /* send dummy value, poll response */
  sdUnselectSlave();
  return data;
}



/* END McuSDCard. */


